development:
  adapter: postgresql
  encoding: utf8
  database: Project2_development
  pool: 5
  username: postgres
  password: password

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: Project2_test
  pool: 5
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: utf8
  database: Project2_production
  pool: 5
  username: postgres
  password: password

cucumber:
  <<: *TEST